site_name: Apache Ranger
site_url: https://kumaab.github.io/ranger-mkdocs/

theme:
  name: material
  logo: assets/asf-logo.png
  palette:
    - scheme: default
      primary: violet
      accent: violet
      toggle:
        icon: material/brightness-7  # ☀️
        name: Switch to dark mode
    - scheme: slate
      primary: purple
      accent: purple
      toggle:
        icon: material/brightness-4  # 🌙
        name: Switch to light mode
  features:
    - navigation.tabs

nav:
  - Home: home/overview.md
  - Getting started:
    - Installation: getting-started/install.md
    - Trino with Ranger: getting-started/trino-with-ranger.md
  - Architecture:
    - Overview: arch/architecture.md
  - Plugins:
    - Trino: plugins/trino.md
  - Services:
    - Ranger Admin: services/admin/service.md
    - Ranger KMS: services/kms/service.md
    - Ranger UserSync: services/usersync/service.md
    - Ranger TagSync: services/tagsync/service.md
  - Features:
    - Governed Data Sharing: features/gds/gds_intro.md
    - Security Zones: 
      - Introduction: features/sec-zone/intro.md
      - APIs: features/sec-zone/apis.md
    - Client Libraries:
        - Introduction: features/client-interface/intro.md
  - Project:
    - Contributing: project/contributing.md
    - Release Process: project/release-process.md
    - ASF:
        - Sponsorship: https://www.apache.org/foundation/sponsorship.html
        - Events: https://www.apache.org/events/current-event.html
        - Privacy: https://privacy.apache.org/policies/privacy-policy-public.html
        - License: https://www.apache.org/licenses/
        - Security: https://www.apache.org/security/
        - Sponsors: https://www.apache.org/foundation/sponsors.html
    - Security:
        - Vulnerabilities Found: project/cve-list.md
  - Releases:
      - Releases: release-notes/index.md
      - 2.8.0: release-notes/2.8.0.md
      - 2.7.0: release-notes/2.7.0.md
      - 2.6.0: release-notes/2.6.0.md
      - 2.5.0: release-notes/2.5.0.md
  - Blog:
    - blog/blog.md

extra:
  homepage: https://ranger.apache.org
  version:
    provider: mike
    default: stable
    alias: true

markdown_extensions:
  - attr_list
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

