name: ci

on:
  push:
    branches: [ main, master ]

permissions:
  contents: write

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git author
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      # weekly cache for mkdocs' .cache to speed up rebuilds
      - name: Compute cache key
        run: echo "cache_id=$(date --utc +%V)" >> "$GITHUB_ENV"

      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install mkdocs-material

      - name: Build (fail on warnings)
        run: mkdocs build --strict

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
